// export 
const works = [
    {
        name: 'Clouds',
        size: '130x168 cm',
        textiles: ' ',
        technique: 'acrylic on canvas',
        exhibition: '',
        workDescr: 'We look up and fold dreams into ornaments. The transparent layers gradually fill in and create volume. No matter, whether you’re soaring into the air or diving into water, you experience a sense of weightlessness.',
        imgSrc: ['./images/works/clouds.jpg', './images/works/clouds-1.jpg'],

    },
    {
        name: 'Faith',
        size: '160x238 cm',
        textiles: 'paper, old newspapers',
        technique: 'paper weaving',
        exhibition: '',
        workDescr: 'FAITH is like a fragile substance: clear, white in color and light, giving an ability to fly. Our words, phrases, the flow of information around distort and  stain the reality and faith, it happens in any language, with no exceptions. It doesn’t let us fly.',
        imgSrc: ['./images/works/faith.jpg', './images/works/faith-1.jpg', './images/works/faith-2.jpg'],

    },
    {
        name: 'Anxious Joy Diptych',
        size: '140х175 cm',
        textiles: 'silk, chiffon, cotton, velvet',
        technique: 'hand stitching',
        exhibition: '',
        workDescr: 'The explosion of emotions, the contrast of feelings is exciting. It is difficult to define with one vector, but this is an explosion of overflowing states. We do not allow ourselves to feel simple rejoice, but it is impossible to stop the overwhelming movement of joy that is experienced by the child inside us. Overflowing with emotions, the desire for movement, brightness. As soon as joyful emotions capture us, the next step is a contrasting feeling that tries to break through and unbalance, shatter us from the inside.',
        imgSrc: ['./images/works/anxious-joy.png', './images/works/anxious-joy-2.png', './images/works/anxious-joy-3.png', './images/works/anxious-joy-4.png'],

    },
    {
        name: 'Relief/ Release',
        size: '175х70 cm',
        textiles: 'silk, chiffon, cotton',
        technique: 'hand stitching',
        exhibition: '',
        workDescr: 'When we are experiencing intense sorrow, frustration or disappointment. We are worried, giving this feeling its place and time. After a strong negative occasion, we experience a short period of relief, letting it go. The finish of any sad and unpleasant event is an opportunity to breathe deeply and purely again, with a willingness to move on.',
        imgSrc: ['./images/works/relief.png', './images/works/relief-2.png', './images/works/relief-3.png'],
    },
    {
        name: 'Emptiness',
        size: '125х50 cm',
        textiles: 'silk, chiffon, cotton',
        technique: 'hand stitching and embroidery',
        exhibition: '',
        workDescr: 'The emptiness of sensations. It almost never happens, there is no vacuum of emotions, however, sometimes we experience emptiness (devastation). Small tendencies of emotions at this moment exist as a hint, as an expression of possibility, not correct, not explicit, not readable…',
        imgSrc: ['./images/works/emptiness.png', './images/works/emptiness-2.png', './images/works/emptiness-3.png'],
    },
    {
        name: 'Sadness/ Frustration',
        size: '125х50 cm',
        textiles: 'silk, chiffon, cotton',
        technique: 'hand stitching and embroidery',
        exhibition: '',
        workDescr: 'Often despite the severity of sorrow, we feel small pieces of enlightenment behind the scene. The main character of sadness is something exhausting inside us, something destructive. Both the good and the bad are smashed together in a dark mix, a clot of the past squeezes us from the inside, folding the space of experiences, and hiding inside.',
        imgSrc: ['./images/works/sadness.png', './images/works/sadness-2.png', './images/works/sadness-3.png'],
    },
    {
        name: 'Hope',
        size: '125х50 cm',
        textiles: 'silk, chiffon, cotton, velvet',
        technique: 'hand stitching',
        exhibition: '',
        workDescr: 'This is as the first warm feeling that fills us after a strong experience. It gently determines the flow of emotions and the direction of sensations. It sparkles with different shades of warm color, thereby creating the illusion of joy, calming down and at the same time setting you up for moving forward. There is still no clear plan of action yet, but lots of warm pieces of canvas excite the imagination, giving us the opportunity to feel the positive direction of our thoughts.',
        imgSrc: ['./images/works/hope.png', './images/works/hope-2.png', './images/works/hope-3.png'],
    },
    {
        name: 'Dreams',
        size: '140x56 cm',
        textiles: 'silk, velour, chiffon, cotton, gauze',
        technique: 'hand stitching',
        exhibition: '',
        workDescr: 'It is only in dreams while sleeping, that we lose ourselves along with the sense of body. We have no clear contours, no age, no experience, no specific past, present and future. It seems that we become free and can travel in time and space. But we still travel through the palaces of our minds, through our lives, through our mistakes and triumphs, through our experiences, including those handed down through generations. It’s as if all of it grounds us and our lightness of being during a dream.',
        imgSrc: ['./images/works/dreams.png', './images/works/dreams-2.jpg', './images/works/dreams-3.jpg'],
    },
    {
        name: 'Irritation',
        size: '125х50 cm',
        textiles: 'silk, chiffon, cotton',
        technique: 'hand stitching',
        exhibition: '',
        workDescr: 'A brief temporary chaos of feelings that has not yet turned into anger, frustration or solace. It is still not easy to cope with feelings and realize what it will lead to. At this moment one experiences clear division of feelings into fragmentary, contradictory parts which still do not allow aggression to break out.Active negativity and inability to find a positive trend of feelings are already forming.',
        imgSrc: ['./images/works/irritation.png', './images/works/irritation-2.png', './images/works/irritation-3.png'],
    },
    {
        name: 'Gaeta',
        size: '250х100 cm',
        textiles: 'canvas',
        technique: 'acrylic',
        exhibition: '',
        workDescr: 'Vision and sensory perception of the city lights. Here, real city lights become flickering flashes, lining up in a discordant ornament. The sea line seems to cut off and emphasize the lights floating in the air and practically jumping over each other. It seems that they are about to line up in proper rows or switch their places, forming a new picture.',
        imgSrc: ['./images/works/gaeta.png'],
    },
    {
        name: 'Female Warmth',
        size: '220x140 cm',
        textiles: 'silk, velour, chiffon, cotton',
        technique: 'hand stitching',
        exhibition: '',
        workDescr: 'The warmth of a mother, the warmth of a sister, the warmth of a friend. A woman’s warmth, soft, streamlined, calm, like nature itself. The feeling of total acceptance, stability. Different shades of a warm palette flowing one into the other. Smooth lines, directed to the centre, create a light, airy vortex, which picks up and envelopes with feminine warmth. ',
        imgSrc: ['./images/works/Female-Warmth.png', './images/works/Female-Warmth-2.jpg', './images/works/Female-Warmth-3.jpg', './images/works/Female-Warmth-4.jpg'],
    },
    {
        name: 'The Wings',
        size: '247х210 cm',
        textiles: 'silk, chiffon',
        technique: 'hand stitching',
        exhibition: '',
        workDescr: 'An exalted image. It can take us to God. Turning to the top, we always rise a little. We ask for the same things in different languages and in different moments, we talk to “Him” and try on “the Wings” – his capabilities.',
        imgSrc: ['./images/works/wings.png'],
    },
    {
        name: 'The Leaf-lake',
        size: '175х75 cm',
        textiles: 'silk, chiffon, cotton',
        technique: 'hand stitching',
        exhibition: '',
        workDescr: 'A tree leaf is a harmonious natural image, a symbol of the naturalness and depth of nature. Looking at it, we experience gentle calm. Plunging into the depths of your own inner nature, you can contemplate water and mountains for endless time. This image clearly traces the trend of folk traditions, the analogy with the textile ethnic blankets technique. Small multi – colored pieces convey the sense of calm and equanimity of nature, a harmonious shimmer of water and greenery colors.',
        imgSrc: ['./images/works/the-leaf-lake.png', './images/works/the-leaf-lake-2.png', './images/works/the-leaf-lake-3.png'],
    },
    {
        name: 'Dark city/Shimmering City',
        size: '140х175 cm',
        textiles: 'silk, chiffon, cotton, velour, gauze',
        technique: 'hand stitching',
        exhibition: '',
        workDescr: 'The dark city. The Shimmering city. The city is never completely dark at night. There are always twinkling lights, lanterns, bright, lively windows. It gives a sense of warmth even if the mood is “November” and everything is very gloomy.',
        imgSrc: ['./images/works/city.jpg', './images/works/city-2.jpg', './images/works/city-3.jpg', './images/works/city-4.jpg'],
    },
]